### ISSUE TITLE
Suspected of not working properly error-handler

### ISSUE THREAD

**Issue by zrebcu411** [FieryCod/KNIT-homepage-back#64] opened 2017-05-24 21:03 UTC
It seems to be error-handler is not working properly. When adding duplicated member to the db, an error in controller is caught with mongo error message about duplication: 

`{ MongoError: E11000 duplicate key error collection: db.members index: username_1 dup key: { : "Username1" }
    at Function.MongoError.create (/home/dominik/Zrebcu/Stronki/KNIT-homepage/KNIT-homepage-back/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11) ...`

 At the same time response body contains error about schema validation fail:

`{ message: 'Response validation failed: failed schema validation',
  code: 'SCHEMA_VALIDATION_FAILED',
  failedValidation: true ...`

Here is the link to the issue branch: https://github.com/FieryCod/KNIT-homepage-back/tree/issue-error-handler

**Comment by k911** [comment] 2017-05-25 09:27
Identified issue: error handler works fine, just passed error has .toJSON() method which changes error response attributes. It is called in res.json(errorResponse).

This should fix issue: https://github.com/FieryCod/KNIT-homepage-back/pull/65

**Comment by FieryCod** [comment] 2017-05-25 10:06
@k911 Looks perfectly fine. @zrebcu411 could you confirm whether the issue is fixed with #65?

**Comment by zrebcu411** [comment] 2017-05-25 11:12
@FieryCod it looks fine now. Res.body contains a message about duplication:
`errcode: 11000,
  code: 'MONGO_ERROR',
  message: 'E11000 duplicate key error collection: db.members index: username_1 dup key: { : "Username1" }' }
`

**Comment by FieryCod** [comment] 2017-05-25 17:19
Perfect :)

**Closed by FieryCod** 2017-05-25 17:19 UTC
